// LightPeek.idl : IDL source for LightPeek
//

// This file will be processed by the MIDL tool to
// produce the type library (LightPeek.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(f36e690c-830d-4fb8-9fd0-f6beb44376f3),
	version(1.0),
]
library LightPeekLib
{
	importlib("stdole2.tlb");
};

