// DllSurrogates.idl: DllSurrogates 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(DllSurrogates.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(DE4972AA-53A3-40DA-9721-47631521682C),
	pointer_default(unique),
	oleautomation

]
interface IMessage : IUnknown
{
	HRESULT InitApartment();
	HRESULT InitWCapture([in] BSTR strMsg);
};
[
	uuid(55BC07C1-5362-4E94-9759-C4CB866FC153),
	version(1.0),
]
library DllSurrogatesLib
{
	importlib("stdole2.tlb");
	[
		uuid(CA287451-6B99-47A0-BF9A-344742E72D3D)
	]
	coclass Message
	{
		interface IMessage;
	};
};

import "shobjidl.idl";
