// DllSurrogates.idl: DllSurrogates 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(DllSurrogates.tlb)和封送处理代码。
// 如果修改了UUID，则 Message.rgs 里的 UUID 也需要一并修改

import "oaidl.idl";
import "ocidl.idl";

typedef struct 
{
	BSTR line;
	int curPos;
} IDLCaptureResult;

[
	object,
	uuid(de4972aa-53a3-40da-9721-47631521682c),
	pointer_default(unique),
	oleautomation

]
interface IMessage : IUnknown
{
	HRESULT InitApartment();
	HRESULT InitWCapture(BSTR lang);
	HRESULT Capture(unsigned char* img, DWORD imgLength, int xPos, int yPos, [out] IDLCaptureResult*result);
};
[
	uuid(55bc07c1-5362-4e94-9759-c4cb866fc153),
	version(1.0),
]
library DllSurrogatesLib
{
	importlib("stdole2.tlb");
	[
		uuid(ca287451-6b99-47a0-bf9a-344742e72d3d)
	]
	coclass Message
	{
		interface IMessage;
	};
};

import "shobjidl.idl";
